<div class="container board"></div>
<script>
    <?php $game = (new \Schrank\TwitterChess\Game()); ?>
    let board = <?= json_encode($game->getBoard()->toArray(), JSON_THROW_ON_ERROR, 512) ?>;

    function buildBoard(board) {
        let i = 0;
        const emptySquares = ['⬛', '⬜'];
        const insertIntoBoard = document.createDocumentFragment();
        let currentRow;
        board.forEach(square => {
            if (i++ % 8 === 0) {
                currentRow = document.createElement('div');
                currentRow.className = 'row';
                insertIntoBoard.appendChild(currentRow);
            }
            let squareElement = document.createElement('div');
            squareElement.textContent = square;
            squareElement.className = emptySquares.indexOf(square) !== -1 ? 'tc-empty' : 'tc-figure';
            currentRow.appendChild(squareElement);
        });
        document.querySelectorAll('.board')[0].appendChild(insertIntoBoard);
    }

    $(function () {
        buildBoard(board);
        $('.board').on('click touch', function (event) {
            let elem = $(event.target);
            if ($('.active') && elem.hasClass('tc-empty')) {
                $.ajax('/api/move/')
            }

            if (elem.text() === '⬛' || elem.text() === '⬜') {
                return;
            }
            $('.active').removeClass('active');
            elem.toggleClass('active');
        });
    });
</script>
