<?php declare(strict_types=1); ?>
<?php

use Ramsey\Uuid\Uuid;

?>

<div class="container board"></div>
<script>
    <?php $id = $_GET['game'] ?? Uuid::uuid5(Uuid::NAMESPACE_DNS, $_SERVER['SERVER_NAME'])->toString(); ?>
    const id = <?= json_encode($id, JSON_THROW_ON_ERROR, 512) ?>;

    function buildBoard(board) {
        let i = 0;
        const emptySquares = ['⬛', '⬜'];
        const insertIntoBoard = document.createDocumentFragment();
        let currentRow;
        let column = 'A';
        let row = 8;
        board.forEach(square => {
            if (i % 8 === 0) {
                currentRow = document.createElement('div');
                currentRow.className = 'row';
                insertIntoBoard.appendChild(currentRow);
            }
            let squareElement = document.createElement('div');
            squareElement.id = column + row.toString(10);
            squareElement.textContent = square;
            squareElement.className = emptySquares.indexOf(square) !== -1 ? 'tc-empty' : 'tc-figure';
            currentRow.appendChild(squareElement);
            column = nextChar(column);
            if (i % 8 === 7) {
                row--;
                column = 'A';
            }
            i++;
        });
        let boardElement = document.querySelectorAll('.board')[0];
        boardElement.textContent = '';
        boardElement.appendChild(insertIntoBoard);
    }

    function nextChar(c) {
        return String.fromCharCode(c.charCodeAt(0) + 1);
    }

    $(function () {
        $.ajax('/api/load/', {
            method: 'post',
            data: {
                id: id
            },
            dataType: 'json',
            success: (response) => {
                buildBoard(response);
            },
            error: (response) => {
                console.log(response.error);
            }
        });
        $('.board').on('click touch', function (event) {
            let elem = $(event.target);
            let activeSquare = $('.active');
            if (activeSquare && elem.hasClass('tc-empty')) {
                $.ajax('/api/move/', {
                    method: 'post',
                    data: {
                        from: activeSquare.attr('id'),
                        to: elem.attr('id'),
                        id: id
                    },
                    dataType: 'json',
                    success: (response) => {
                        buildBoard(response);
                    },
                    error: (response) => {
                        // TODO implement proper error handling
                        console.log(response.error);
                    }
                });
            }

            if (elem.text() === '⬛' || elem.text() === '⬜') {
                return;
            }
            activeSquare.removeClass('active');
            elem.toggleClass('active');
        });
    });
</script>
