name: Unit tests

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      steps:
        - name: Checkout
          uses: actions/checkout@v1

        - name: Setup PHP
          uses: shivammathur/setup-php@v1
          with:
            php-version: '7.4'

#        - name: PHPUnit
#          run: vendor/bin/phpunit tests
